"""
Prometheus metrics for ResumeRank.

Naming convention follows the official Prometheus best practices:
  <namespace>_<subsystem>_<unit>
  https://prometheus.io/docs/practices/naming/

All durations use seconds (SI base unit).
All throughput counters use _total suffix.
Histograms use SLO-aligned buckets tuned for local GPU inference (~60 s/resume).
"""

from prometheus_client import Counter, Gauge, Histogram

# ============================================================
# AI EVALUATION (per provider)
# ============================================================

EVALUATIONS = Counter(
    "resumerank_ai_evaluations_total",
    "AI evaluation attempts by provider and outcome (success | failure).",
    ("provider", "outcome"),
)

EVALUATION_DURATION = Histogram(
    "resumerank_ai_evaluation_duration_seconds",
    "End-to-end AI evaluation latency in seconds, from prompt send to parsed result.",
    ("provider",),
    # SLO-aligned buckets: 5 s → 5 min (local GPU inference is slow)
    buckets=(5, 10, 20, 30, 45, 60, 90, 120, 180, 240, 300),
)

# Tokens generated per second — GPU throughput signal (Ollama native metric)
AI_TOKENS_GENERATED = Counter(
    "resumerank_ai_tokens_generated_total",
    "Total output tokens generated by the AI model, by provider.",
    ("provider",),
)

AI_TOKENS_PER_SECOND = Histogram(
    "resumerank_ai_tokens_per_second",
    "Output token generation speed (tok/s). Primary GPU throughput indicator.",
    ("provider",),
    buckets=(1, 2, 5, 10, 15, 20, 30, 50, 75, 100),
)

# ============================================================
# SCREENING WORKFLOW
# ============================================================

SCREENING_RUNS = Counter(
    "resumerank_screening_runs_total",
    "Total screening runs triggered, by final status (completed | failed).",
    ("status",),
)

SCREENING_DURATION = Histogram(
    "resumerank_screening_duration_seconds",
    "Wall-clock duration of an entire screening run in seconds.",
    buckets=(60, 300, 600, 900, 1800, 3600, 7200, 14400),
)

SCREENING_CANDIDATES_PROCESSED = Counter(
    "resumerank_screening_candidates_total",
    "Total candidates processed across all screenings, by outcome (success | failure).",
    ("outcome",),
)

# ============================================================
# PER-CANDIDATE LATENCY  ← most important SLO metric
# ============================================================

CANDIDATE_PROCESSING_DURATION = Histogram(
    "resumerank_candidate_processing_duration_seconds",
    (
        "End-to-end per-candidate latency (download + extract + AI eval + DB write). "
        "Query P95/P99 in Grafana to set SLOs."
    ),
    ("stage",),  # total | extraction | evaluation | scoring
    # 5 s granularity up to 10 min — covers the ~60 s/resume observed baseline
    buckets=(5, 10, 20, 30, 45, 60, 90, 120, 180, 240, 300, 420, 600),
)

# ============================================================
# THROUGHPUT
# ============================================================

CANDIDATE_THROUGHPUT = Gauge(
    "resumerank_candidate_throughput_per_hour",
    (
        "Rolling throughput: candidates successfully processed per hour. "
        "Updated at the end of each screening run."
    ),
)

# ============================================================
# BATCH THROTTLING
# ============================================================

BATCH_COOLDOWNS = Counter(
    "resumerank_batch_cooldowns_total",
    "Number of inter-batch cooldown sleeps fired to prevent GPU saturation.",
    ("screening_id",),
)

BATCH_COOLDOWN_DURATION = Histogram(
    "resumerank_batch_cooldown_duration_seconds",
    "Actual sleep duration per batch cooldown (seconds).",
    buckets=(5, 10, 15, 20, 30, 45, 60, 90, 120),
)

# ============================================================
# PIPELINE STAGES (download + parse)
# ============================================================

RESUME_DOWNLOADS = Counter(
    "resumerank_resume_downloads_total",
    "Resume download attempts by outcome (success | failure).",
    ("outcome",),
)

RESUME_DOWNLOAD_DURATION = Histogram(
    "resumerank_resume_download_duration_seconds",
    "Time taken to fetch and extract text from a resume URL.",
    buckets=(0.5, 1, 2, 5, 10, 20, 30, 60),
)

RESUME_PARSE_FAILURES = Counter(
    "resumerank_resume_parse_failures_total",
    "Resume text extraction failures (empty or unreadable content).",
)
